import 'package:flutter/material.dart';
import '../services/world_time.dart';

class ChooseLocation extends StatefulWidget {
  const ChooseLocation({super.key});

  @override
  State<ChooseLocation> createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {

  List<WorldTime> locations = [
    WorldTime(url: 'Africa/Abidjan', location: 'Abidjã', flag: 'costa_do_marfim.png', isDaytime: true),
    WorldTime(url: 'Africa/Accra', location: 'Acra', flag: 'gana.png', isDaytime: true),
    WorldTime(url: 'Africa/Addis_Ababa', location: 'Adis Ababa', flag: 'ethiopia.png', isDaytime: true),
    WorldTime(url: 'Africa/Algiers', location: 'Argel', flag: 'algeria.png', isDaytime: true),
    WorldTime(url: 'Africa/Asmara', location: 'Asmara', flag: 'eritreia.png', isDaytime: true),
    WorldTime(url: 'Africa/Asmera', location: 'Asmera', flag: 'eritreia.png', isDaytime: true),
    WorldTime(url: 'Africa/Bamako', location: 'Bamaco', flag: 'mali.png', isDaytime: true),
    WorldTime(url: 'Africa/Bangui', location: 'Bangui', flag: 'central_republic_african.png', isDaytime: true),
    WorldTime(url: 'Africa/Banjul', location: 'Banjul', flag: 'gambia.png', isDaytime: true),
    WorldTime(url: 'Africa/Bissau', location: 'Bissau', flag: 'guinea_bissau.png', isDaytime: true),
    WorldTime(url: 'Africa/Blantyre', location: 'Blantire', flag: 'malawi.png', isDaytime: true),
    WorldTime(url: 'Africa/Brazzaville', location: 'Brazavile', flag: 'congo.png', isDaytime: true),
    WorldTime(url: 'Africa/Bujumbura', location: 'Bujumbura', flag: 'burundi.png', isDaytime: true),
    WorldTime(url: 'Africa/Cairo', location: 'Cairo', flag: 'egito.png', isDaytime: true),
    WorldTime(url: 'Africa/Casablanca', location: 'Casablanca', flag: 'marrocos.png', isDaytime: true),
    WorldTime(url: 'Africa/Ceuta', location: 'Ceuta', flag: 'ceuta.png', isDaytime: true),
    WorldTime(url: 'Africa/Conakry', location: 'Conacri', flag: 'guinea.png', isDaytime: true),
    WorldTime(url: 'Africa/Dakar', location: 'Dacar', flag: 'senegal.png', isDaytime: true),
    WorldTime(url: 'Africa/Dar_es_Salaam', location: 'Dar es Salaam', flag: 'tanzania.png', isDaytime: true),
    WorldTime(url: 'Africa/Djibouti', location: 'Djibuti', flag: 'djibouti.png', isDaytime: true),
    WorldTime(url: 'Africa/Douala', location: 'Duala', flag: 'cameroon.png', isDaytime: true),
    WorldTime(url: 'Africa/El_Aaiun', location: 'El Aiune', flag: 'saara_ocidental.png', isDaytime: true),
    WorldTime(url: 'Africa/Freetown', location: 'Freetown', flag: 'serra_leoa.png', isDaytime: true),
    WorldTime(url: 'Africa/Gaborone', location: 'Gaborone', flag: 'botswana.png', isDaytime: true),
    WorldTime(url: 'Africa/Harare', location: 'Harare', flag: 'zimbabwe.png', isDaytime: true),
    WorldTime(url: 'Africa/Johannesburg', location: 'Joanesburgo', flag: 'south_africa.png', isDaytime: true),
    WorldTime(url: 'Africa/Juba', location: 'Juba', flag: 'south_sudan.png', isDaytime: true),
    WorldTime(url: 'Africa/Kampala', location: 'Campala', flag: 'uganda.png', isDaytime: true),
    WorldTime(url: 'Africa/Khartoum', location: 'Cartum', flag: 'sudan.png', isDaytime: true),
    WorldTime(url: 'Africa/Kigali', location: 'Quigali', flag: 'ruanda.png', isDaytime: true),
    WorldTime(url: 'Africa/Kinshasa', location: 'Quinxassa', flag: 'democratic_republic_of_the_congo.png', isDaytime: true),
    WorldTime(url: 'Africa/Lagos', location: 'Lagos', flag: 'nigeria.png', isDaytime: true),
    WorldTime(url: 'Africa/Libreville', location: 'Libreville', flag: 'gabon.png', isDaytime: true),
    WorldTime(url: 'Africa/Lome', location: 'Lomé', flag: 'togo.png', isDaytime: true),
    WorldTime(url: 'Africa/Luanda', location: 'Luanda', flag: 'angola.png', isDaytime: true),
    WorldTime(url: 'Africa/Lubumbashi', location: 'Lubumbashi', flag: 'democratic_republic_of_the_congo.png', isDaytime: true),
    WorldTime(url: 'Africa/Lusaka', location: 'Lusaca', flag: 'zambia.png', isDaytime: true),
    WorldTime(url: 'Africa/Malabo', location: 'Malabo', flag: 'equatorial_guinea.png', isDaytime: true),
    WorldTime(url: 'Africa/Maputo', location: 'Maputo', flag: 'mozambique.png', isDaytime: true),
    WorldTime(url: 'Africa/Maseru', location: 'Maseru', flag: 'lesoto.png', isDaytime: true),
    WorldTime(url: 'Africa/Mbabane', location: 'Mebabane', flag: 'eswatini.png', isDaytime: true),
    WorldTime(url: 'Africa/Mogadishu', location: 'Mogadíscio', flag: 'somalia.png', isDaytime: true),
    WorldTime(url: 'Africa/Monrovia', location: 'Monróvia', flag: 'liberia.png', isDaytime: true),
    WorldTime(url: 'Africa/Nairobi', location: 'Nairóbi', flag: 'kenya.png', isDaytime: true),
    WorldTime(url: 'Africa/Ndjamena', location: 'Jamena', flag: 'chade.png', isDaytime: true),
    WorldTime(url: 'Africa/Niamey', location: 'Niamei', flag: 'niger.png', isDaytime: true),
    WorldTime(url: 'Africa/Nouakchott', location: 'Nouakchott', flag: 'mauritania.png', isDaytime: true),
    WorldTime(url: 'Africa/Ouagadougou', location: 'Uagadugu', flag: 'burkina_faso.png', isDaytime: true),
    WorldTime(url: 'Africa/Porto-Novo', location: 'Porto Novo', flag: 'benin.png', isDaytime: true),
    WorldTime(url: 'Africa/Sao_Tome', location: 'São Tomé', flag: 'sao_tome_e_principe.png', isDaytime: true),
    WorldTime(url: 'Africa/Timbuktu', location: 'Tombuctu', flag: 'mali.png', isDaytime: true),
    WorldTime(url: 'Africa/Tripoli', location: 'Trípoli', flag: 'libya.png', isDaytime: true),
    WorldTime(url: 'Africa/Tunis', location: 'Tunes', flag: 'tunisia.png', isDaytime: true),
    WorldTime(url: 'Africa/Windhoek', location: 'Vinduque', flag: 'namibia.png', isDaytime: true),
    WorldTime(url: 'America/Adak', location: 'Adak', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Anchorage', location: 'Anchorague', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Anguilla', location: 'Anguila', flag: 'anguila.png', isDaytime: true),
    WorldTime(url: 'America/Antigua', location: 'Antígua', flag: 'antigua_and_barbuda.png', isDaytime: true),
    WorldTime(url: 'America/Araguaina', location: 'Araguaína', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Buenos_Aires', location: 'Buenos Aires', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Catamarca', location: 'Catamarca', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/ComodRivadavia', location: 'Comodoro Rivadaria', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Cordoba', location: 'Córdova', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Jujuy', location: 'Jujuy', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/La_Rioja', location: 'La Rioja', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Mendoza', location: 'Mendoza', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Rio_Gallegos', location: 'Río Gallegos', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Salta', location: 'Salta', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/San_Juan', location: 'San Juan', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/San_Luis', location: 'San Luis', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Tucuman', location: 'Tucumã', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Ushuaia', location: 'Ushuaia', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Aruba', location: 'Aruba', flag: 'aruba.png', isDaytime: true),
    WorldTime(url: 'America/Asuncion', location: 'Assunção', flag: 'paraguai.png', isDaytime: true),
    WorldTime(url: 'America/Atikokan', location: 'Atikokan', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Atka', location: 'Atka', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Bahia', location: 'Bahia', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Bahia_Banderas', location: 'Bahía de Banderas', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Barbados', location: 'Barbados', flag: 'barbados.png', isDaytime: true),
    WorldTime(url: 'America/Belem', location: 'Belém', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Belize', location: 'Belize', flag: 'belize.png', isDaytime: true),
    WorldTime(url: 'America/Blanc_Sablon', location: 'Blanc-Sablon', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Boa_Vista', location: 'Boa Vista', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Bogota', location: 'Bogotá', flag: 'colombia.png', isDaytime: true),
    WorldTime(url: 'America/Boise', location: 'Boise', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Buenos_Aires', location: 'Buenos Aires', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Cambridge_Bay', location: 'Cambridge Bay', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Campo_Grande', location: 'Campo Grande', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Cancun', location: 'Cancún', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Caracas', location: 'Caracas', flag: 'venezuela.png', isDaytime: true),
    WorldTime(url: 'America/Catamarca', location: 'Catamarca', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Cayenne', location: 'Cayenne', flag: 'guiana_francesa.png', isDaytime: true),
    WorldTime(url: 'America/Cayman', location: 'Cayman', flag: 'ilhas_cayman.png', isDaytime: true),
    WorldTime(url: 'America/Chicago', location: 'Chicago', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Chihuahua', location: 'Chihuahua', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Ciudad_Juarez', location: 'Ciudad Juárez', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Coral_Harbour', location: 'Coral Harbour', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Cordoba', location: 'Córdova', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Costa_Rica', location: 'Costa Rica', flag: 'costa_rica.png', isDaytime: true),
    WorldTime(url: 'America/Creston', location: 'Creston', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Cuiaba', location: 'Cuiabá', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Curacao', location: 'Curaçao', flag: 'curacao.png', isDaytime: true),
    WorldTime(url: 'America/Danmarkshavn', location: 'Danmarkshavn', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Dawson', location: 'Dawson', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Dawson_Creek', location: 'Dawson Creek', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Denver', location: 'Denver', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Detroit', location: 'Detroit', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Dominica', location: 'Dominica', flag: 'dominica.png', isDaytime: true),
    WorldTime(url: 'America/Edmonton', location: 'Edmonton', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Eirunepe', location: 'Eirunepé', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/El_Salvador', location: 'El Salvador', flag: 'el_salvador.png', isDaytime: true),
    WorldTime(url: 'America/Ensenada', location: 'Ensenada', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Fort_Nelson', location: 'Fort Nelson', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Fort_Wayne', location: 'Fort Wayne', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Fortaleza', location: 'Fortaleza', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Glace_Bay', location: 'Glace Bay', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Godthab', location: 'Godthab', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Goose_Bay', location: 'Goose Bay', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Grand_Turk', location: 'Grande Turca', flag: 'ilhas_turcas_e_caicos.png', isDaytime: true),
    WorldTime(url: 'America/Grenada', location: 'Granada', flag: 'granada.png', isDaytime: true),
    WorldTime(url: 'America/Guadeloupe', location: 'Guadalupe', flag: 'guadalupe.png', isDaytime: true),
    WorldTime(url: 'America/Guatemala', location: 'Guatemala', flag: 'guatemala.png', isDaytime: true),
    WorldTime(url: 'America/Guayaquil', location: 'Guaiaquil', flag: 'equador.png', isDaytime: true),
    WorldTime(url: 'America/Guyana', location: 'Guiana', flag: 'guiana.png', isDaytime: true),
    WorldTime(url: 'America/Halifax', location: 'Halifax', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Havana', location: 'Havana', flag: 'cuba.png', isDaytime: true),
    WorldTime(url: 'America/Hermosillo', location: 'Hermosillo', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Indianapolis', location: 'Indianápolis', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Knox', location: 'Knox', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Marengo', location: 'Marengo', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Petersburg', location:  'Petersburg', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Tell_City', location: 'Tell City', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Vevay', location: 'Vevay', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Vincennes', location: 'Vincennes', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Winamac', location: 'Winamac', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indianapolis', location: 'Indianápolis', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Inuvik', location: 'Inuvik', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Iqaluit', location: 'Iqaluit', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Jamaica', location: 'Jamaica', flag: 'jamaica.png', isDaytime: true),
    WorldTime(url: 'America/Jujuy', location: 'Jujuy', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Juneau', location: 'Juneau', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Kentucky/Louisville', location: 'Louisville', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Kentucky/Monticello', location: 'Monticello', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Knox_IN', location: 'Knox', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Kralendijk', location: 'Kralendijk', flag: 'nederland.png', isDaytime: true),
    WorldTime(url: 'America/La_Paz', location: 'La Paz', flag: 'bolivia.png', isDaytime: true),
    WorldTime(url: 'America/Lima', location: 'Lima', flag: 'peru.png', isDaytime: true),
    WorldTime(url: 'America/Los_Angeles', location: 'Los Angeles', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Louisville', location: 'Louisville', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Lower_Princes', location: 'Lower Princes', flag: 'nederland.png', isDaytime: true),
    WorldTime(url: 'America/Maceio', location: 'Maceió', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Managua', location: 'Manágua', flag: 'nicaragua.png', isDaytime: true),
    WorldTime(url: 'America/Manaus', location: 'Manaus', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Marigot', location: 'Marigot', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'America/Martinique', location: 'Martinica', flag: 'martinica.png', isDaytime: true),
    WorldTime(url: 'America/Matamoros', location: 'Matamoros', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Mazatlan', location: 'Mazatlán', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Mendoza', location: 'Mendoza', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Menominee', location: 'Menominee', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Merida', location: 'Mérida', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Metlakatla', location: 'Metlakatla', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Mexico_City', location: 'Cidade do México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Miquelon', location: 'Miquelão', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'America/Moncton', location: 'Moncton', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Monterrey', location: 'Monterrey', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Montevideo', location: 'Montevidéu', flag: 'uruguai.png', isDaytime: true),
    WorldTime(url: 'America/Montreal', location: 'Montreal', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Montserrat', location: 'Monserrate', flag: 'monserrate.png', isDaytime: true),
    WorldTime(url: 'America/Nassau', location: 'Nassau', flag: 'bahamas.png', isDaytime: true),
    WorldTime(url: 'America/New_York', location: 'Nova Iorque', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Nipigon', location: 'Nipigon', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Nome', location: 'Nome', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Noronha', location: 'Fernando de Noronha', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/North_Dakota/Beulah', location: 'Beulah', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/North_Dakota/Center', location: 'Center', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/North_Dakota/New_Salem', location: 'New Salem', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Nuuk', location: 'Nuuk', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Ojinaga', location: 'Ojinaga', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Panama', location: 'Panamá', flag: 'panama.png', isDaytime: true),
    WorldTime(url: 'America/Pangnirtung', location: 'Pangnirtung', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Paramaribo', location: 'Paramaribo', flag: 'suriname.png', isDaytime: true),
    WorldTime(url: 'America/Phoenix', location: 'Phoenix', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Port-au-Prince', location: 'Port-au-Prince', flag: 'haiti.png', isDaytime: true),
    WorldTime(url: 'America/Port_of_Spain', location: 'Porto da Espanha', flag: 'trindade_e_tobago.png', isDaytime: true),
    WorldTime(url: 'America/Porto_Acre', location: 'Porto Acre', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Porto_Velho', location: 'Porto Velho', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Puerto_Rico', location: 'Porto Rico', flag: 'porto_rico.png', isDaytime: true),
    WorldTime(url: 'America/Punta_Arenas', location: 'Punta Arenas', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'America/Rainy_River', location: 'Rainy River', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Rankin_Inlet', location: 'Rankin Inlet', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Recife', location: 'Recife', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Regina', location: 'Regina', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Resolute', location: 'Resolute', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Rio_Branco', location: 'Rio Branco', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Rosario', location: 'Rosário', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Santa_Isabel', location: 'Santa Isabel', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Santarem', location: 'Santarém', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Santiago', location: 'Santiago', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'America/Santo_Domingo', location: 'Santo Domingo', flag: 'dominican_republic.png', isDaytime: true),
    WorldTime(url: 'America/Sao_Paulo', location: 'São Paulo', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Scoresbysund', location: 'Ittoqqortoormiit', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Shiprock', location: 'Shiprock', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Sitka', location: 'Sitka', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/St_Barthelemy', location: 'São Bartolomeu', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'America/St_Johns', location: 'St. John', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/St_Kitts', location: 'São Cristóvão e Neves', flag: 'saint_kitts_and_nevis.png', isDaytime: true),
    WorldTime(url: 'America/St_Lucia', location: 'Santa Lúcia', flag: 'saint_lucia.png', isDaytime: true),
    WorldTime(url: 'America/St_Thomas', location: 'St. Thomas', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/St_Vincent', location: 'São Vicente e Granadinas', flag: 'saint_vicent_and_the_grenadines.png', isDaytime: true),
    WorldTime(url: 'America/Swift_Current', location: 'Swift Current', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Tegucigalpa', location: 'Tegucigalpa', flag: 'honduras.png', isDaytime: true),
    WorldTime(url: 'America/Thule', location: 'Thule', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'America/Thunder_Bay', location: 'Thunder Bay', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Tijuana', location: 'Tijuana', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Toronto', location: 'Toronto', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Tortola', location: 'Tortola', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'America/Vancouver', location: 'Vancouver', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Virgin', location: 'Virgínia', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Whitehorse', location: 'Whitehorse', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Winnipeg', location: 'Winnipeg', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Yakutat', location: 'Yakutat', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Yellowknife', location: 'Yellowknife', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Casey', location: 'Casey', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Davis', location: 'Davis', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/DumontDUrville', location: 'DumontDUrville', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Macquarie', location: 'Macquarie', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Mawson', location: 'Mawson', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/McMurdo', location: 'McMurdo', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Palmer', location: 'Palmer', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Rothera', location: 'Rothera', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/South_Pole', location: 'Polo Sul', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Syowa', location: 'Syowa', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Troll', location: 'Troll', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Vostok', location: 'Vostok', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Arctic/Longyearbyen', location: 'Longyearbyen', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Asia/Aden', location: 'Adem', flag: 'yemen.png', isDaytime: true),
    WorldTime(url: 'Asia/Almaty', location: 'Almati', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Amman', location: 'Amã', flag: 'jordan.png', isDaytime: true),
    WorldTime(url: 'Asia/Anadyr', location: 'Anadyr', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Aqtau', location: 'Aqtau', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Aqtobe', location: 'Aqtöbe', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Ashgabat', location: 'Ashgabat', flag: 'turkmenistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Ashkhabad', location: 'Asgabade', flag: 'turkmenistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Atyrau', location: 'Atyrau', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Baghdad', location: 'Bagdá', flag: 'iraque.png', isDaytime: true),
    WorldTime(url: 'Asia/Bahrain', location: 'Bahrein', flag: 'bahrein.png', isDaytime: true),
    WorldTime(url: 'Asia/Baku', location: 'Bacu', flag: 'azerbaijan.png', isDaytime: true),
    WorldTime(url: 'Asia/Bangkok', location: 'Banguecoque', flag: 'thailand.png', isDaytime: true),
    WorldTime(url: 'Asia/Barnaul', location: 'Barnaul', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Beirut', location: 'Beirute', flag: 'lebanon.png', isDaytime: true),
    WorldTime(url: 'Asia/Bishkek', location: 'Bisqueque', flag: 'kyrgyzstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Brunei', location: 'Brunei', flag: 'brunei.png', isDaytime: true),
    WorldTime(url: 'Asia/Calcutta', location: 'Calcutá', flag: 'india.png', isDaytime: true),
    WorldTime(url: 'Asia/Chita', location: 'Chitá', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Choibalsan', location: 'Choibalsan', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Chongqing', location: 'Xunquim', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Chungking', location: 'Chung Hing Sam Lam', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Colombo', location: 'Colombo', flag: 'sri_lanka.png', isDaytime: true),
    WorldTime(url: 'Asia/Dacca', location: 'Dacca', flag: 'bangladesh.png', isDaytime: true),
    WorldTime(url: 'Asia/Damascus', location: 'Damasco', flag: 'syria.png', isDaytime: true),
    WorldTime(url: 'Asia/Dhaka', location: 'Daca', flag: 'bangladesh.png', isDaytime: true),
    WorldTime(url: 'Asia/Dili', location: 'Díli', flag: 'timor_leste.png', isDaytime: true),
    WorldTime(url: 'Asia/Dubai', location: 'Dubai', flag: 'uae.png', isDaytime: true),
    WorldTime(url: 'Asia/Dushanbe', location: 'Duxambé', flag: 'tajikistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Famagusta', location: 'Famagusta', flag: 'chipre_do_norte.png', isDaytime: true),
    WorldTime(url: 'Asia/Gaza', location: 'Gaza', flag: 'palestina.png', isDaytime: true),
    WorldTime(url: 'Asia/Harbin', location: 'Harbin', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Hebron', location: 'Hebrom', flag: 'palestina.png', isDaytime: true),
    WorldTime(url: 'Asia/Ho_Chi_Minh', location: 'Ho Chi Minh', flag: 'vietnam.png', isDaytime: true),
    WorldTime(url: 'Asia/Hong_Kong', location: 'Hong Kong', flag: 'hong_kong.png', isDaytime: true),
    WorldTime(url: 'Asia/Hovd', location: 'Khovd', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Irkutsk', location: 'Irkutsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Istanbul', location: 'Istambul', flag: 'turquia.png', isDaytime: true),
    WorldTime(url: 'Asia/Jakarta', location: 'Jacarta', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Jayapura', location: 'Jayapura', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Jerusalem', location: 'Jerusalém', flag: 'israel.png', isDaytime: true),
    WorldTime(url: 'Asia/Kabul', location: 'Cabul', flag: 'afghanistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Kamchatka', location: 'Camecháteca', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Karachi', location: 'Carachi', flag: 'pakistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Kashgar', location: 'Casgar', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Kathmandu', location: 'Catmandu', flag: 'nepal.png', isDaytime: true),
    WorldTime(url: 'Asia/Katmandu', location: 'Katmandu', flag: 'nepal.png', isDaytime: true),
    WorldTime(url: 'Asia/Khandyga', location: 'Khandyga', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kolkata', location: 'Calcutá', flag: 'india.png', isDaytime: true),
    WorldTime(url: 'Asia/Krasnoyarsk', location: 'Krasnoiarsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kuala_Lumpur', location: 'Kuala Lumpur', flag: 'malaysia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kuching', location: 'Kuching', flag: 'malaysia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kuwait', location: 'Kuwait', flag: 'kuwait.png', isDaytime: true),
    WorldTime(url: 'Asia/Macao', location: 'Macao', flag: 'macau.png', isDaytime: true),
    WorldTime(url: 'Asia/Macau', location: 'Macau', flag: 'macau.png', isDaytime: true),
    WorldTime(url: 'Asia/Magadan', location: 'Magadan', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Makassar', location: 'Macáçar', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Manila', location: 'Manila', flag: 'filipinas.png', isDaytime: true),
    WorldTime(url: 'Asia/Muscat', location: 'Mascat', flag: 'oman.png', isDaytime: true),
    WorldTime(url: 'Asia/Nicosia', location: 'Nicosia', flag: 'chipre.png', isDaytime: true),
    WorldTime(url: 'Asia/Novokuznetsk', location: 'Novokuznetsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Novosibirsk', location: 'Novosibirsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Omsk', location: 'Omsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Oral', location: 'Oral', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Phnom_Penh', location: 'Phnom Penh', flag: 'camboja.png', isDaytime: true),
    WorldTime(url: 'Asia/Pontianak', location: 'Pontianak', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Pyongyang', location: 'Pyongyang', flag: 'coreia_do_norte.png', isDaytime: true),
    WorldTime(url: 'Asia/Qatar', location: 'Catar', flag: 'catar.png', isDaytime: true),
    WorldTime(url: 'Asia/Qostanay', location: 'Qostanay', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Qyzylorda', location: 'Qyzylorda', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Rangoon', location: 'Rangum', flag: 'myanmar.png', isDaytime: true),
    WorldTime(url: 'Asia/Riyadh', location: 'Riade', flag: 'saudi_arabia.png', isDaytime: true),
    WorldTime(url: 'Asia/Saigon', location: 'Saigon', flag: 'vietnam.png', isDaytime: true),
    WorldTime(url: 'Asia/Sakhalin', location: 'Sacalina', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Samarkand', location: 'Samarcanda', flag: 'uzbekistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Seoul', location: 'Seul', flag: 'coreia_do_sul.png', isDaytime: true),
    WorldTime(url: 'Asia/Shanghai', location: 'Xangai', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Singapore', location: 'Singapura', flag: 'singapura.png', isDaytime: true),
    WorldTime(url: 'Asia/Srednekolymsk', location: 'Srednekolymsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Taipei', location: 'Taipei', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Tashkent', location: 'Tasquente', flag: 'uzbekistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Tbilisi', location: 'Tiblíssi', flag: 'georgia.png', isDaytime: true),
    WorldTime(url: 'Asia/Tehran', location: 'Teerã', flag: 'iran.png', isDaytime: true),
    WorldTime(url: 'Asia/Tel_Aviv', location: 'Tel Aviv', flag: 'israel.png', isDaytime: true),
    WorldTime(url: 'Asia/Thimbu', location: 'Thimbu', flag: 'bhutan.png', isDaytime: true),
    WorldTime(url: 'Asia/Thimphu', location: 'Thimphu', flag: 'bhutan.png', isDaytime: true),
    WorldTime(url: 'Asia/Tokyo', location: 'Tóquio', flag: 'japan.png', isDaytime: true),
    WorldTime(url: 'Asia/Tomsk', location: 'Tomsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Ujung_Pandang', location: 'Ujung Pandang', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Ulaanbaatar', location: 'Ulã Bator', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Ulan_Bator', location: 'Ulan Bator', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Urumqi', location: 'Ürümqi', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Ust-Nera', location: 'Ust-Nera', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Vientiane', location: 'Vientiane', flag: 'laos.png', isDaytime: true),
    WorldTime(url: 'Asia/Vladivostok', location: 'Vladivostoque', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Yakutsk', location: 'Iacutusque', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Yangon', location: 'Rangum', flag: 'myanmar.png', isDaytime: true),
    WorldTime(url: 'Asia/Yekaterinburg', location: 'Ecaterimburgo', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Yerevan', location: 'Erevã', flag: 'armenia.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Azores', location: 'Açores', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Bermuda', location: 'Bermuda', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Canary', location: 'Canary', flag: 'espanha.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Cape_Verde', location: 'Cabo Verde', flag: 'cabo_verde.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Faeroe', location: 'Faroé', flag: 'dinamarca.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Faroe', location: 'Faroe', flag: 'dinamarca.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Jan_Mayen', location: 'Jan Mayen', flag: 'noruega.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Madeira', location: 'Madeira', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Reykjavik', location: 'Reiquiavique', flag: 'iceland.png', isDaytime: true),
    WorldTime(url: 'Atlantic/South_Georgia', location: 'Geórgia do Sul', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Atlantic/St_Helena', location: 'Santa Helena', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Stanley', location: 'Stanley', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Australia/ACT', location: 'ACT', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Adelaide', location: 'Adelaide', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Brisbane', location: 'Brisbane', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Broken_Hill', location: 'Broken Hill', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Canberra', location: 'Camberra', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Currie', location: 'Currie', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Darwin', location: 'Darwin', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Eucla', location: 'Eucla', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Hobart', location: 'Hobart', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/LHI', location: 'LHI', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Lindeman', location: 'Lindeman', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Lord_Howe', location: 'Lord Howe', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Melbourne', location: 'Melbourne', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/NSW', location: 'NSW', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/North', location: 'North', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Perth', location: 'Perth', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Queensland', location: 'Queensland', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/South', location: 'South', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Sydney', location: 'Sydney', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Tasmania', location: 'Tasmânia', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Victoria', location: 'Victoria', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/West', location: 'West', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Yancowinna', location: 'Yancowinna', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Brazil/Acre', location: 'Acre', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'Brazil/DeNoronha', location: 'Fernando de Noronha', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'Brazil/East', location: 'Leste', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'Brazil/West', location: 'Oeste', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'CET', location: 'CET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'CST6CDT', location: 'CST6CDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Canada/Atlantic', location: 'Atlantic', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Central', location: 'Central', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Eastern', location: 'Eastern', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Mountain', location: 'Mountain', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Newfoundland', location: 'Newfoundland and Labrador', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Pacific', location: 'Pacific', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Saskatchewan', location: 'Sascachevão', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Yukon', location: 'Yukon', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Chile/Continental', location: 'Continental', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'Chile/EasterIsland', location: 'Ilha de Páscoa', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'Cuba', location: 'Cuba', flag: 'cuba.png', isDaytime: true),
    WorldTime(url: 'EET', location: 'EET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'EST', location: 'EST', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'EST5EDT', location: 'EST5EDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Egypt', location: 'Egito', flag: 'egito.png', isDaytime: true),
    WorldTime(url: 'Eire', location: 'Éire', flag: 'irlanda.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT', location: 'GMT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+0', location: 'GMT+0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+1', location: 'GMT+1', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+10', location: 'GMT+10', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+11', location: 'GMT+11', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+12', location: 'GMT+12', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+2', location: 'GMT+2', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+3', location: 'GMT+3', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+4', location: 'GMT+4', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+5', location: 'GMT+5', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+6', location: 'GMT+6', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+7', location: 'GMT+7', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+8', location: 'GMT+8', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+9', location: 'GMT+9', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-0', location: 'GMT-0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-1', location: 'GMT-1', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-10', location: 'GMT-10', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-11', location: 'GMT-11', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-12', location: 'GMT-12', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-13', location: 'GMT-13', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-14', location: 'GMT-14', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-2', location: 'GMT-2', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-3', location: 'GMT-3', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-4', location: 'GMT-4', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-5', location: 'GMT-5', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-6', location: 'GMT-6', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-7', location: 'GMT-7', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-8', location: 'GMT-8', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-9', location: 'GMT-9', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT0', location: 'GMT0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/Greenwich', location: 'Greenwich', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/UCT', location: 'UCT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/UTC', location: 'UTC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/Universal', location: 'Universal', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/Zulu', location: 'Zulu', flag: 'south_africa.png', isDaytime: true),
    WorldTime(url: 'Europe/Amsterdam', location: 'Amsterdã', flag: 'nederland.png', isDaytime: true),
    WorldTime(url: 'Europe/Andorra', location: 'Andorra', flag: 'andorra.png', isDaytime: true),
    WorldTime(url: 'Europe/Astrakhan', location: 'Astracã', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Athens', location: 'Atenas', flag: 'greece.png', isDaytime: true),
    WorldTime(url: 'Europe/Belfast', location: 'Belfaste', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Belgrade', location: 'Belgrado', flag: 'serbia.png', isDaytime: true),
    WorldTime(url: 'Europe/Berlin', location: 'Berlim', flag: 'alemanha.png', isDaytime: true),
    WorldTime(url: 'Europe/Bratislava', location: 'Bratislava', flag: 'slovakia.png', isDaytime: true),
    WorldTime(url: 'Europe/Brussels', location: 'Bruxelas', flag: 'belgium.png', isDaytime: true),
    WorldTime(url: 'Europe/Bucharest', location: 'Bucareste', flag: 'romania.png', isDaytime: true),
    WorldTime(url: 'Europe/Budapest', location: 'Budapeste', flag: 'hungria.png', isDaytime: true),
    WorldTime(url: 'Europe/Busingen', location: 'Büsingen no Alto Reno', flag: 'alemanha.png', isDaytime: true),
    WorldTime(url: 'Europe/Chisinau', location: 'Quixinau', flag: 'moldavia.png', isDaytime: true),
    WorldTime(url: 'Europe/Copenhagen', location: 'Copenhagen', flag: 'dinamarca.png', isDaytime: true),
    WorldTime(url: 'Europe/Dublin', location: 'Dublin', flag: 'irlanda.png', isDaytime: true),
    WorldTime(url: 'Europe/Gibraltar', location: 'Gibraltar', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Guernsey', location: 'Guernsey', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Helsinki', location: 'Helsínquia', flag: 'finland.png', isDaytime: true),
    WorldTime(url: 'Europe/Isle_of_Man', location: 'Ilha dos Homens', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Istanbul', location: 'Istambul', flag: 'turquia.png', isDaytime: true),
    WorldTime(url: 'Europe/Jersey', location: 'Jersey', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Kaliningrad', location: 'Kaliningrado', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Kiev', location: 'Kiev', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Kirov', location: 'Kirov', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Kyiv', location: 'Kyiv', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Lisbon', location: 'Lisboa', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'Europe/Ljubljana', location: 'Liubliana', flag: 'slovenia.png', isDaytime: true),
    WorldTime(url: 'Europe/London', location: 'Londres', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Luxembourg', location: 'Luxemburgo', flag: 'luxemburgo.png', isDaytime: true),
    WorldTime(url: 'Europe/Madrid', location: 'Madri', flag: 'espanha.png', isDaytime: true),
    WorldTime(url: 'Europe/Malta', location: 'Malta', flag: 'malta.png', isDaytime: true),
    WorldTime(url: 'Europe/Mariehamn', location: 'Mariehamn', flag: 'finland.png', isDaytime: true),
    WorldTime(url: 'Europe/Minsk', location: 'Minsk', flag: 'belarus.png', isDaytime: true),
    WorldTime(url: 'Europe/Monaco', location: 'Mônaco', flag: 'monaco.png', isDaytime: true),
    WorldTime(url: 'Europe/Moscow', location: 'Moscou', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Nicosia', location: 'Nicosia', flag: 'chipre.png', isDaytime: true),
    WorldTime(url: 'Europe/Oslo', location: 'Oslo', flag: 'noruega.png', isDaytime: true),
    WorldTime(url: 'Europe/Paris', location: 'Paris', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Europe/Podgorica', location: 'Podgorica', flag: 'montenegro.png', isDaytime: true),
    WorldTime(url: 'Europe/Prague', location: 'Praga', flag: 'czech_republic.png', isDaytime: true),
    WorldTime(url: 'Europe/Riga', location: 'Riga', flag: 'latvia.png', isDaytime: true),
    WorldTime(url: 'Europe/Rome', location: 'Roma', flag: 'italy.png', isDaytime: true),
    WorldTime(url: 'Europe/Samara', location: 'Samara', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/San_Marino', location: 'San Marino', flag: 'san_marino.png', isDaytime: true),
    WorldTime(url: 'Europe/Sarajevo', location: 'Sarajevo', flag: 'bosnia_and_herzegovina.png', isDaytime: true),
    WorldTime(url: 'Europe/Saratov', location: 'Saratov', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Simferopol', location: 'Simferopol', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Skopje', location: 'Escópia', flag: 'north_macedonia.png', isDaytime: true),
    WorldTime(url: 'Europe/Sofia', location: 'Sofia', flag: 'bulgaria.png', isDaytime: true),
    WorldTime(url: 'Europe/Stockholm', location: 'Estocolmo', flag: 'sweden.png', isDaytime: true),
    WorldTime(url: 'Europe/Tallinn', location: 'Talim', flag: 'estonia.png', isDaytime: true),
    WorldTime(url: 'Europe/Tirane', location: 'Tirana', flag: 'albania.png', isDaytime: true),
    WorldTime(url: 'Europe/Tiraspol', location: 'Tiraspol', flag: 'moldavia.png', isDaytime: true),
    WorldTime(url: 'Europe/Ulyanovsk', location: 'Ulianovsk', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Uzhgorod', location: 'Ujhorod', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Vaduz', location: 'Vaduz', flag: 'liechtenstein.png', isDaytime: true),
    WorldTime(url: 'Europe/Vatican', location: 'Vaticano', flag: 'vaticano.png', isDaytime: true),
    WorldTime(url: 'Europe/Vienna', location: 'Viena', flag: 'austria.png', isDaytime: true),
    WorldTime(url: 'Europe/Vilnius', location: 'Vilnius', flag: 'lithuania.png', isDaytime: true),
    WorldTime(url: 'Europe/Volgograd', location: 'Volgogrado', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Warsaw', location: 'Varsóvia', flag: 'poland.png', isDaytime: true),
    WorldTime(url: 'Europe/Zagreb', location: 'Zagreb', flag: 'croatia.png', isDaytime: true),
    WorldTime(url: 'Europe/Zaporozhye', location: 'Zaporizhzhia', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Zurich', location: 'Zurique', flag: 'swiss.png', isDaytime: true),
    WorldTime(url: 'GB', location: 'GB', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GB-Eire', location: 'GB-Eire', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT', location: 'GMT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT+0', location: 'GMT+0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT-0', location: 'GMT-0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT0', location: 'GMT0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Greenwich', location: 'Greenwich', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'HST', location: 'HST', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Hongkong', location: 'Hong Kong', flag: 'hong_kong.png', isDaytime: true),
    WorldTime(url: 'Iceland', location: 'Islândia', flag: 'iceland.png', isDaytime: true),
    WorldTime(url: 'Indian/Antananarivo', location: 'Antananarivo', flag: 'madagascar.png', isDaytime: true),
    WorldTime(url: 'Indian/Chagos', location: 'Chagos', flag: 'mauritius.png', isDaytime: true),
    WorldTime(url: 'Indian/Christmas', location: 'Christmas', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Indian/Cocos', location: 'Cocos', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Indian/Comoro', location: 'Comoro', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Indian/Kerguelen', location: 'Kerguelen', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Indian/Mahe', location: 'Mahé', flag: 'seychelles.png', isDaytime: true),
    WorldTime(url: 'Indian/Maldives', location: 'Maldivas', flag: 'maldivas.png', isDaytime: true),
    WorldTime(url: 'Indian/Mauritius', location: 'Maurícia', flag: 'mauritius.png', isDaytime: true),
    WorldTime(url: 'Indian/Mayotte', location: 'Mayotte', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Indian/Reunion', location: 'Reunion', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Iran', location: 'Irã', flag: 'iran.png', isDaytime: true),
    WorldTime(url: 'Israel', location: 'Israel', flag: 'israel.png', isDaytime: true),
    WorldTime(url: 'Jamaica', location: 'Jamaica', flag: 'jamaica.png', isDaytime: true),
    WorldTime(url: 'Japan', location: 'Japão', flag: 'japan.png', isDaytime: true),
    WorldTime(url: 'Kwajalein', location: 'Kwajalein', flag: 'ilhas_marshall.png', isDaytime: true),
    WorldTime(url: 'Libya', location: 'Líbia', flag: 'libya.png', isDaytime: true),
    WorldTime(url: 'MET', location: 'MET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'MST', location: 'MST', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'MST7MDT', location: 'MST7MDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Mexico/BajaNorte', location: 'Baja Norte', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'Mexico/BajaSur', location: 'Baja Sur', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'Mexico/General', location: 'General', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'NZ', location: 'NZ', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'NZ-CHA', location: 'NZ-CHA', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Navajo', location: 'Navajo', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'PRC', location: 'PRC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'PST8PDT', location: 'PST8PDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Pacific/Apia', location: 'Apia', flag: 'samoa.png', isDaytime: true),
    WorldTime(url: 'Pacific/Auckland', location: 'Auckland', flag: 'new_zealand.png', isDaytime: true),
    WorldTime(url: 'Pacific/Bougainville', location: 'Bougainville', flag: 'papua_new_guinea.png', isDaytime: true),
    WorldTime(url: 'Pacific/Chatham', location: 'Chatham', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Chuuk', location: 'Chuuk', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Easter', location: 'Páscoa', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'Pacific/Efate', location: 'Efate', flag: 'vanuatu.png', isDaytime: true),
    WorldTime(url: 'Pacific/Enderbury', location: 'Enderbury', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Pacific/Fakaofo', location: 'Fakaofo', flag: 'new_zealand.png', isDaytime: true),
    WorldTime(url: 'Pacific/Fiji', location: 'Fiji', flag: 'fiji.png', isDaytime: true),
    WorldTime(url: 'Pacific/Funafuti', location: 'Funafuti', flag: 'tuvalu.png', isDaytime: true),
    WorldTime(url: 'Pacific/Galapagos', location: 'Galapagos', flag: 'equador.png', isDaytime: true),
    WorldTime(url: 'Pacific/Gambier', location: 'Gambier', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Guadalcanal', location: 'Guadalcanal', flag: 'solomon_islands.png', isDaytime: true),
    WorldTime(url: 'Pacific/Guam', location: 'Guam', flag: 'guam.png', isDaytime: true),
    WorldTime(url: 'Pacific/Honolulu', location: 'Honolulu', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Johnston', location: 'Johnston', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kanton', location: 'Kanton', flag: 'kiribati.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kiritimati', location: 'Quiritimati', flag: 'kiribati.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kosrae', location: 'Kosrae', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kwajalein', location: 'Kwajalein', flag: 'ilhas_marshall.png', isDaytime: true),
    WorldTime(url: 'Pacific/Majuro', location: 'Majuro', flag: 'ilhas_marshall.png', isDaytime: true),
    WorldTime(url: 'Pacific/Marquesas', location: 'Marquesas', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Midway', location: 'Midway', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Nauru', location: 'Nauru', flag: 'nauru.png', isDaytime: true),
    WorldTime(url: 'Pacific/Niue', location: 'Niuê', flag: 'niue.png', isDaytime: true),
    WorldTime(url: 'Pacific/Norfolk', location: 'Norfolque', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Noumea', location: 'Numeá', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Pago_Pago', location: 'Pago Pago', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Palau', location: 'Palau', flag: 'palau.png', isDaytime: true),
    WorldTime(url: 'Pacific/Pitcairn', location: 'Ilhas Pitcairn', flag: 'ilhas_pitcairn.png', isDaytime: true),
    WorldTime(url: 'Pacific/Pohnpei', location: 'Pohnpei', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Ponape', location: 'Ponape', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Port_Moresby', location: 'Porto Moresby', flag: 'papua_new_guinea.png', isDaytime: true),
    WorldTime(url: 'Pacific/Rarotonga', location: 'Rarotonga', flag: 'new_zealand.png', isDaytime: true),
    WorldTime(url: 'Pacific/Saipan', location: 'Saipã', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Samoa', location: 'Samoa', flag: 'samoa.png', isDaytime: true),
    WorldTime(url: 'Pacific/Tahiti', location: 'Tahiti', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Tarawa', location: 'Taraua', flag: 'kiribati.png', isDaytime: true),
    WorldTime(url: 'Pacific/Tongatapu', location: 'Tongatapu', flag: 'tonga.png', isDaytime: true),
    WorldTime(url: 'Pacific/Truk', location: 'Truk', flag: 'papua_new_guinea.png', isDaytime: true),
    WorldTime(url: 'Pacific/Wake', location: 'Wake', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Wallis', location: 'Wallis', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Yap', location: 'Yap', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Poland', location: 'Polônia', flag: 'poland.png', isDaytime: true),
    WorldTime(url: 'Portugal', location: 'Portugal', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'ROC', location: 'ROC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'ROK', location: 'ROK', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Singapore', location: 'Singapura', flag: 'singapura.png', isDaytime: true),
    WorldTime(url: 'Turkey', location: 'Turquia', flag: 'turquia.png', isDaytime: true),
    WorldTime(url: 'UCT', location: 'UCT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'US/Alaska', location: 'Alasca', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Aleutian', location: 'Aleutian', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Arizona', location: 'Arizona', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Central', location: 'Central', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/East-Indiana', location: 'East-Indiana', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Eastern', location: 'Eastern', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Hawaii', location: 'Havaí', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Indiana-Starke', location: 'Indiana-Starke', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Michigan', location: 'Michigan', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Mountain', location: 'Mountain', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Pacific', location: 'Pacific', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Samoa', location: 'Samoa', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'UTC', location: 'UTC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Universal', location: 'Universal', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'W-SU', location: 'W-SU', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'WET', location: 'WET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Zulu', location: 'Zulu', flag: 'south_africa.png', isDaytime: true),
  ];

  void updateTime(index) async {
    WorldTime instance = locations[index];
    await instance.getTime();
    // navigate to home screen
    Navigator.pop(context, {
      'location': instance.location,
      'flag': instance.flag,
      'time': instance.time,
      'isDaytime': instance.isDaytime,
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        backgroundColor: Colors.blue[900],
        title: Text('Escolha uma Localização'),
        centerTitle: true,
        elevation: 0,
      ),
      body: ListView.builder(
        itemCount: locations.length,
        itemBuilder: (context, index){
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 1.0, horizontal: 4.0),
            child: Card(
              child: ListTile(
                onTap: () {
                  updateTime(index);
                },
                title: Text(locations[index].location),
                leading: CircleAvatar(
                  backgroundImage: AssetImage('assets/${locations[index].flag}'),
                ),
              ),
            ),
          );
        }
      ),
    );
  }
}
